### PR TITLE
Model, refresh new data after updated

### PR DESCRIPTION
**Pull request by Yahasana**
fixed model loss its data (e.g. primary key) after updated to db

### CODE REVIEW

**Comment by mruz** [comment]
It shouldn't lose it's data, we don't remove primary key here:
https://github.com/ice/framework/pull/244/files#diff-adc4d2a2f6f7dca511a6e8073769eb86R378
Also as I said before https://github.com/ice/framework/pull/202#discussion_r221505817, maybe we could move to _fields()_ this https://github.com/ice/framework/pull/244/files#diff-adc4d2a2f6f7dca511a6e8073769eb86R413.

**Comment by Yahasana** [comment]
`$m->update(['a' => 1]);`

$m has no primary key now

**Comment by mruz** [comment]
I added some tests, but they passed https://github.com/ice/framework/pull/246/files
Is the primary key an array? or auto-increment is false?

**Comment by Yahasana** [comment]
Oops, I change my repos to support `$m->update(['a' => 1]);`.
the correct way to work with yours repos should be
```
$m->a = 1;
$m->update(['a']);
```
goddamn ugly implement

**Comment by mruz** [comment]
Both ways should work... I just wonder why they first isn't working for you.

**Comment by mruz** [comment]
Fields with data are merged here https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L240, so we don't need to merge after. We just need rollback if failed https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L421.

**Comment by Yahasana** [comment]
[L240](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L240) only works for the case `$m->update()` without `fields` parameter or `$m->update(['logins' => 1])` with empty `$this->fields` but doesn't work for `$m->update(['logins'])`.

primary key are removed [L226](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L266), and other unrelated data fields are removed at [L243](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L243) or [L257](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L257) or [L260](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L260). 
[L378](https://github.com/ice/framework/blob/dev/ice/mvc/model.zep#L378) make the changes happen.

EDIT: check pr #248 plz

**Comment by mruz** [comment]
Right, your fix should work then. Could you please merge the tests here #248?

**Pull request merged**
