### PR TITLE
db query signature

### LINKED ISSUE #166: add db::query($sql, $filter, $options)
I found there is [Q&A](https://github.com/ice/framework/issues/101) for this feature. it'd be fine to add a helper method to run native sql

### PR DESCRIPTION
**Pull request by Yahasana**
fixed #166

### CODE REVIEW

**Comment by Yahasana** [comment]
Ping @mruz 
```php
$sql = 'SELECT * FROM `users` WHERE `status` = :status';
$params = ['status' => 1];
$query = $this->db->getClient()->prepare($sql);
$result = $query->execute($params);
```
vs
```php
$sql = 'SELECT * FROM `users` WHERE `status` = :status';
$params = ['status' => 1];
$result = $this->db->query($sql,  $params);
```
ref PDO [query](http://php.net/manual/en/pdo.query.php)

**Comment by mruz** [comment]
Ok, but it will be hard to implement it in the mongo, could you then remove it from the mongo driver and interface?

**Comment by Yahasana** [comment]
new and clean PR

**Comment by mruz** [comment]
Thanks

**Pull request closed without merging**
