### PR TITLE
Build, add mongodb prototype

### PR DESCRIPTION
**Pull request by mruz**

### CODE REVIEW

**Comment by mruz** [comment]
I should rebase instead merge..

**Comment by mruz** [comment]
By default forward uses current data e.g. `/test/first/1` and getParams() on the forwarded request contains parametres from first action, on the second `/test/second/1` parameters will be cleared.
```php
class TestController extends Front
{

    public function firstAction()
    {
        $f = $this->dispatcher->forward([
            'handler' => 'test',
            'action' => 'return'
        ], true);

        $d = $this->dump->vars(
            $f->getReturnedValue(),
            $f->getParams()
        );
        $this->view->setContent($d);
    }

    public function secondAction()
    {
        $f = $this->dispatcher->forward([
            'handler' => 'test',
            'action' => 'return'
        ], true, true);

        $d = $this->dump->vars(
            $f->getReturnedValue(),
            $f->getParams()
        );
        $this->view->setContent($d);
    }

    public function returnAction()
    {
        return 2;
    }
}
```

PS. You can call `$f->getActiveHandler()` to get the previous return from `this->dispatch()`.

**Comment by mruz** [comment]
@Yahasana I posted it here.

**Comment by Yahasana** [comment]
this is what i means, if people don't read the code, it's very hard to understand what this `clear` does
```php
    public function secondAction()
    {
        $f = $this->dispatcher->reset()      // reset dispatcher to the default
            ->forward([
                'handler' => 'test',
                'action' => 'return'
            ], true);
    }
```

**Comment by Yahasana** [comment]
Can't wait the new release to start new project, please release v1.4 ASAP

**Comment by mruz** [comment]
Changes are on dev branch, so you could run:
```
git clone --depth=1 https://github.com/ice/framework.git
cd framework/
./install
```
to have v1.4

**Comment by Yahasana** [comment]
Oops, im working at Windows OS. hard for me to compile this ext dll

**Pull request merged**
